### ISSUE TITLE
IPv6 IP addresses

### ISSUE THREAD

**Issue by chrmarti** [apocas/docker-modem#105]
The regex parsing the DOCKER_HOST URI does not support IPv6 IP addresses: https://github.com/apocas/docker-modem/blob/99fcf0d10521f974dbe335a47a09ecf30ca6c1a2/lib/modem.js#L28

E.g., `'tcp://[::1]:12345'` would split at the second colon instead of the last. You could use Node.js' 'url' module instead of a regex.

**Comment by apocas** [comment]
Just pushed a fix to master. Will publish it later tonight :)

Node.js's url module doesn't handle strings without a protocol specified. (which is used in a few use cases in Docker)
When a protocol isn't specified, docker-modem defaults to tcp:// then it used Node.js URL.

**Comment by apocas** [comment]
Published in v2.0.1

**Comment by chrmarti** [comment]
@apocas Thanks for the quick fix!
