### ISSUE TITLE
8be3b43 clutters output

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [apocas/docker-modem#116]
Commit 8be3b43291aaa5660bdafcea4396c708585056c6 seems to have added the `console.log` to the code:
https://github.com/apocas/docker-modem/blob/8be3b43291aaa5660bdafcea4396c708585056c6/lib/modem.js#L404
Is this on purpose? I don't think it's good practise for libraries/modules to do logging automatically. If on purpose, please consider using [debug](https://www.npmjs.com/package/debug) instead.

**Comment by apocas** [comment]
Fixed and published.
It was left behind :/
