### ISSUE TITLE
npm and github diverge ?

### ISSUE THREAD

**Issue by rafipiccolo** [apocas/docker-modem#131]
Hello,

i can see that version 2.1.4 is latest.
improvements were done, in particular the ability to connect with ssh and private key but they are not on available on npm.

can you push a new version to npm with current source code from github please ?

**Comment by apocas** [comment]
Yes there are a few changes yet to be published.
They will be published tonight :)

**Comment by apocas** [comment]
Done

**Comment by rafipiccolo** [comment]
works for me :) thx !
