### ISSUE TITLE
Update ssh2 dependency

### ISSUE THREAD

**Issue by gjasny** [apocas/docker-modem#135]
Hello,

Could you please update the used version of the `ssh2` dependency to at least `1.0.0` and publish a new release?
That would solve [GHSL-2020-123](https://securitylab.github.com/advisories/GHSL-2020-123-mscdex-ssh2/).

Thanks,
Gregor

**Comment by antikaspar** [comment]
@apocas Thank you.

**Comment by gjasny** [comment]
Fixed with 0b24b61f4a92ab4dcc8bd3e4b3c49e279eec8af0 / [v3.0.3](https://github.com/apocas/docker-modem/releases/tag/v3.0.3).
