### ISSUE TITLE
Why does followProgress require JSON output?

### ISSUE THREAD

**Issue by merlindru** [apocas/docker-modem#138]
`followProgress` attempts to [parse](https://github.com/apocas/docker-modem/blob/8556ad38cf5a022b22f50920fae6b08d2ac3f207/lib/modem.js#L430) all stream data as JSON. Why is that the case?

I'm using dockerode and would like to log the (pretty-printed, not in JSON) stdout of a container to the console. Is there any way to use followProgress this way?

Thanks!!

**Comment by apocas** [comment]
Docker already return that data in JSON, followProgress just parses it.
You stringify it again, or just don't use followProgress and implement your own strategy using the stream directly :)
