### ISSUE TITLE
Wrong type on buffer response

### ISSUE THREAD

**Issue by gallynero** [apocas/docker-modem#149]
I am trying to make the log examples and they do not work and send the following error:

`stream.on('data', processData);
         ^
TypeError: stream.on is not a function
    at Modem.demuxStream (/workspace/1_Project/1_Sources/node_modules/docker-modem/lib/modem.js:410:10)`

Because the returned stream is of type Buffer and not of type ReadableStream, I think the bug is in this line:

https://github.com/apocas/docker-modem/blob/52ae729745b5e62752a342a535afece6135d674d/lib/modem.js#L300

Which should be:

`var json = utils.parseJSON(result) || Readable.from(buffer);`

I will send a pull request with the change please review it.

**Comment by q0rban** [comment]
Looks like this can be closed now as #150 has been merged.

**Comment by apocas** [comment]
Crap, in reality this shouldn't be a stream.
The logs method send the "isStream" parameter if the "follow" parameter is true.

Docker-modem only returns a stream if the isStream is specified. I missed this.

The logs example work. Did you change the "follow" parameter to false?

**Comment by apocas** [comment]
If JSON parsing fails we should just return the string, instead of the buffer though.
