### ISSUE TITLE
[Proposal] add error event handler

### ISSUE THREAD

**Issue by Fhwang0926** [apocas/docker-modem#155]
There is currently no part of the error event processing Anyone else think they should add?

```js

function getCause(isStream, res, json, callback) {
    var chunks = '';
    if (isStream) {
      res.on('data', function (chunk) {
        chunks += chunk;
      });
      res.on('end', function () {
        callback(null, utils.parseJSON(chunks) || chunks);
      });
    } else {
      callback(null, json);
    }
  }

```

During exec processing in the [dockerode ](https://github.com/apocas/dockerode) project, there was an issue where error event processing was absent when the container was restarted, so the exception was not processed

So I'm leaving my opinion here

**Comment by apocas** [comment]
https://github.com/apocas/docker-modem/commit/8e054177ded397b6166159fd723b0e45445d3ae7#diff-55d7eacad4cdcc83064806c86ad0c5acfdee1dce88730cf041108408b5e0197bL399
