### ISSUE TITLE
X-Registry-Config Header

### ISSUE THREAD

**Issue by ekristen** [apocas/docker-modem#47]
So with docker 1.7.0 and forward, the build endpoint (and possibly others) wants the `X-Registry-Config` header which is the base64 encoded contents of the `.docker/config.json` or the `.dockercfg` file (the first being the new formatted config file, the second being the legacy location.

A quick fix for this would be at Line 119 of modem.js simply putting `optionsf.headers['X-Registry-Config'] = optionsf.headers['X-Registry-Auth']` but I am unsure if this is the right move. I could see putting in a new option registryconf or something in the options to populate this file and then just doing `= options.registryconfig || optionsf.headers['X-Registry-Auth']` 

Either way this is a change that needs to be made soon to keep up with the docker api versions, without it, the build process will not work with version 1.7.x and greater.

**Comment by apocas** [comment]
Sorry I'm a bit lost.

X-Registry-Auth where the authentication base64 string resides.
How is this related with the X-Registry-Config from build?

**Comment by apocas** [comment]
Check this out:
https://github.com/apocas/docker-modem/commit/dad8f8b3f950bff8f93ed89ab916c001c839a40a
https://github.com/apocas/dockerode

**Comment by apocas** [comment]
Published in dockerode v2.2.2 and docker-modem v0.2.6

**Comment by ekristen** [comment]
I will test it out. Thanks
