### ISSUE TITLE
issues for large build context when invoking buildImage api

### ISSUE THREAD

**Issue by ghost** [apocas/docker-modem#50]
the buildImage uses fs.readFileSync on the source tar.
1. this blocks the event-loop.

worse yet, if the tar file is large, a buffer is allocated the size of the tar file. for a 1GB build context, for example, you exceed the max buffer size node allows.
you'll have to recompile v8 to get this to work.

pull request for working with stream instead opened.

**Comment by apocas** [comment]
Streams already supported. https://github.com/apocas/dockerode/issues/128

More details in https://github.com/apocas/docker-modem/pull/49
