### ISSUE TITLE
Modem.followProgress crashes with TypeError

### ISSUE THREAD

**Issue by doganyazar** [apocas/docker-modem#62]
Once in a while, I have this exception caused by the following code:
```
TypeError: Cannot read property 'pipe' of null
    at Modem.followProgress (/booya/dunya/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:289:9)
    at /booya/dunya/lib/client.js:127:38
    at /booya/dunya/node_modules/dockerode/lib/docker.js:69:5
    at /booya/dunya/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:235:7
    at IncomingMessage.<anonymous> (/booya/dunya/node_modules/dockerode/node_modules/dock
```

```javascript
const debug = require('debug')('docker')
const dockerode = require('dockerode')({
    host: 'http://localhost',
    port: 2375
})

function pullImage(imageName) {
    return new Promise(function(resolve, reject) {
        dockerode.pull(imageName, function(err, stream) {
            if (err) {
                reject(err)
            }
            dockerode.modem.followProgress(stream, onFinished, onProgress)
            function onFinished(err, output) {
                if (err) {
                    reject(new Error(err))
                }
                resolve(output)
            }
            function onProgress(event) {
                debug(event)
            }
        })
    })
}
```

$ docker -v
Docker version 1.10.3, build 20f81dd

Could not really track down the issue. Any ideas?

**Comment by doganyazar** [comment]
After looking this again, it looks like it is a programming error so closing the issue. 

Should be
```
if (err) {
    return reject(err)
}
```

**Comment by bholbrook73** [comment]
@doganyazar - I run into the same problem - but only intermittently and I'm not returned any error so rejecting the err doesn't help. Do you have any more information on this?

**Comment by doganyazar** [comment]
@bholbrook73 sorry I have not had any problems with it after that.

**Comment by KBPratap** [comment]
I have this issue, on some user machines this works fine but for some it throws the following errors:

    TypeError: Cannot read property 'pipe' of null
        at Modem.followProgress (/data/app/node_modules/docker-modem/lib/modem.js:316:10)

Following is the implementation

    docker.pull(repoTag, function(err, stream) {
        docker.modem.followProgress(stream, onFinished, onProgress);
        function onFinished(err, output) {
            ....
        }
        function onProgress(event) {
            ....
        }
    }

**Comment by MartinMuzatko** [comment]
same here. It only happens sometimes

**Comment by bj00rn** [comment]
same error here. intermittent

**Comment by kratoon3** [comment]
Still happens to me if the image does not exists.
