### ISSUE TITLE
Support customized headers

### ISSUE THREAD

**Issue by edwardproxy** [apocas/docker-modem#67]
We are using docker engine swarm mode and one scenario is:
On one swarm worker, our service, which is running inside a docker container, will make some remote api calls to swarm manager leader. Now we want to enable the TLS for docker daemon on the manager leaders.
To make those remote api calls, we use dockerode module, and what we want to do is to set the headers(Host: <common name>), then make the remote call by IP, not the common name, so we don't have to set it in /etc/hosts to tell what IP the common name will be resolved to.

e.g.

https://github.com/apocas/dockerode

``` javascript
var docker = new Docker({
  protocol: 'https',
  host: '192.168.1.10',
  headers:{Host: 'my-common-name'}, // we need it!!!
  port: process.env.DOCKER_PORT || 2375,
  ca: fs.readFileSync('ca.pem'),
  cert: fs.readFileSync('cert.pem'),
  key: fs.readFileSync('key.pem')
});
```

And in docker-modem:

``` javascript
var optionsf = {
    path: address,
    method: options.method,
    // headers when making this dial, if not, then the headers when new the modem object, and 
    // then no headers
    headers: options.headers || self.headers || {},
    key: self.key,
    cert: self.cert,
    ca: self.ca
  };
```

**Comment by ypjin** [comment]
This seems not necessary for docker-modem since it supports setting headers per request, but it's good to have this.
