### ISSUE TITLE
Update Dependencies Of Your Project So That NPM Shrinkwrap Will Work

### ISSUE THREAD

**Issue by mashaalmemon** [apocas/docker-modem#71]
Hi There,

Listing in the package dependencies is the npm package  `follow-redirects@0.0.3`. That package has a dependency for underscore but no version is specified.

As a result when using the `npm shrinkwrap` command in my project, I am experiencing this error #https://github.com/npm/npm/issues/11493 

Is there any way you can update and release a  your dependencies to a more recent version of `follow-redirects`. They have fixed this issue in later releases by modifying their package.json dependencies and not having any dependencies. 

Your package is used by the npm package `docker-modem` which will use any 0.3.x release. Thus if you update your package version to 0.3.2, this problem would be fixed for myself and any other user who uses npm shrinkwrap. 

Let me know if you require any clarification.

**Comment by apocas** [comment]
Merged will published later today:
https://github.com/apocas/docker-modem/pull/68

**Comment by mashaalmemon** [comment]
@apocas , many thanks.

**Comment by apocas** [comment]
Fixed and published.
