### ISSUE TITLE
Broken followProgress()

### ISSUE THREAD

**Issue by ak1394** [apocas/docker-modem#88]
It looks like the recent release which updated JSONStream from 0.10.0 to 1.3.2 has broken followProgress(). 
With version 1.0.5 onFinished, onProgress callbacks are no longer being called.

**Comment by andyedwardsdfdl** [comment]
Possibly related to https://github.com/apocas/dockerode/issues/439 ?
If so, then `docker-modem@1.0.6` will fix this.

**Comment by apocas** [comment]
Correct :)
